package factory.pageobjects;

public class Invoice_Nursing_Home {

	String SCENARIO;
	String PROVIDER_NAME;
	String INVOICE_TYPE;
	String RATE_CHANGE_FLAG;
	String REFUND_FLAG;
	String MEDICARE_COVER_FLAG;
	String MEDICARE_COVER_COMMENT;
	String INSURED_LEAVE_FACILITY_FLAG;
	String INSURED_LEAVE_FACILITY_COMMENT;
	String SERVICE_START_DATE;
	String SERVICE_END_DATE;
	String SERVICE_CHARGES;
	String INDIVIDUAL_CHARGES_SERVICE_TYPE;
	String INDIVIDUAL_CHARGES_SERVICE_CHARGE;
	String ADDITIONAL_COMMENT;
	String FRAUD_DISCLOSURE_FLAG;

	public String getSCENARIO() {
		return SCENARIO;
	}

	public void setSCENARIO(String sCENARIO) {
		SCENARIO = sCENARIO;
	}

	public String getPROVIDER_NAME() {
		return PROVIDER_NAME;
	}

	public void setPROVIDER_NAME(String pROVIDER_NAME) {
		PROVIDER_NAME = pROVIDER_NAME;
	}

	public String getINVOICE_TYPE() {
		return INVOICE_TYPE;
	}

	public void setINVOICE_TYPE(String iNVOICE_TYPE) {
		INVOICE_TYPE = iNVOICE_TYPE;
	}

	public String getRATE_CHANGE_FLAG() {
		return RATE_CHANGE_FLAG;
	}

	public void setRATE_CHANGE_FLAG(String rATE_CHANGE_FLAG) {
		RATE_CHANGE_FLAG = rATE_CHANGE_FLAG;
	}

	public String getREFUND_FLAG() {
		return REFUND_FLAG;
	}

	public void setREFUND_FLAG(String rEFUND_FLAG) {
		REFUND_FLAG = rEFUND_FLAG;
	}

	public String getMEDICARE_COVER_FLAG() {
		return MEDICARE_COVER_FLAG;
	}

	public void setMEDICARE_COVER_FLAG(String mEDICARE_COVER_FLAG) {
		MEDICARE_COVER_FLAG = mEDICARE_COVER_FLAG;
	}

	public String getMEDICARE_COVER_COMMENT() {
		return MEDICARE_COVER_COMMENT;
	}

	public void setMEDICARE_COVER_COMMENT(String mEDICARE_COVER_COMMENT) {
		MEDICARE_COVER_COMMENT = mEDICARE_COVER_COMMENT;
	}

	public String getINSURED_LEAVE_FACILITY_FLAG() {
		return INSURED_LEAVE_FACILITY_FLAG;
	}

	public void setINSURED_LEAVE_FACILITY_FLAG(String iNSURED_LEAVE_FACILITY_FLAG) {
		INSURED_LEAVE_FACILITY_FLAG = iNSURED_LEAVE_FACILITY_FLAG;
	}

	public String getINSURED_LEAVE_FACILITY_COMMENT() {
		return INSURED_LEAVE_FACILITY_COMMENT;
	}

	public void setINSURED_LEAVE_FACILITY_COMMENT(String iNSURED_LEAVE_FACILITY_COMMENT) {
		INSURED_LEAVE_FACILITY_COMMENT = iNSURED_LEAVE_FACILITY_COMMENT;
	}

	public String getSERVICE_START_DATE() {
		return SERVICE_START_DATE;
	}

	public void setSERVICE_START_DATE(String sERVICE_START_DATE) {
		SERVICE_START_DATE = sERVICE_START_DATE;
	}

	public String getSERVICE_END_DATE() {
		return SERVICE_END_DATE;
	}

	public void setSERVICE_END_DATE(String sERVICE_END_DATE) {
		SERVICE_END_DATE = sERVICE_END_DATE;
	}

	public String getSERVICE_CHARGES() {
		return SERVICE_CHARGES;
	}

	public void setSERVICE_CHARGES(String sERVICE_CHARGES) {
		SERVICE_CHARGES = sERVICE_CHARGES;
	}

	public String getINDIVIDUAL_CHARGES_SERVICE_TYPE() {
		return INDIVIDUAL_CHARGES_SERVICE_TYPE;
	}

	public void setINDIVIDUAL_CHARGES_SERVICE_TYPE(String iNDIVIDUAL_CHARGES_SERVICE_TYPE) {
		INDIVIDUAL_CHARGES_SERVICE_TYPE = iNDIVIDUAL_CHARGES_SERVICE_TYPE;
	}

	public String getINDIVIDUAL_CHARGES_SERVICE_CHARGE() {
		return INDIVIDUAL_CHARGES_SERVICE_CHARGE;
	}

	public void setINDIVIDUAL_CHARGES_SERVICE_CHARGE(String iNDIVIDUAL_CHARGES_SERVICE_CHARGE) {
		INDIVIDUAL_CHARGES_SERVICE_CHARGE = iNDIVIDUAL_CHARGES_SERVICE_CHARGE;
	}

	public String getADDITIONAL_COMMENT() {
		return ADDITIONAL_COMMENT;
	}

	public void setADDITIONAL_COMMENT(String aDDITIONAL_COMMENT) {
		ADDITIONAL_COMMENT = aDDITIONAL_COMMENT;
	}

	public String getFRAUD_DISCLOSURE_FLAG() {
		return FRAUD_DISCLOSURE_FLAG;
	}

	public void setFRAUD_DISCLOSURE_FLAG(String fRAUD_DISCLOSURE_FLAG) {
		FRAUD_DISCLOSURE_FLAG = fRAUD_DISCLOSURE_FLAG;
	}

	public void setAttribute(String currentField, String field) {
		
		
	}
	
	

	
	

}
